### PR TITLE
save media-type escaped in verifier filename, and use in verify config and status

### LINKED ISSUE #3704: Loss of content tree image type for container downloaded but not loaded during reboot
As discussed with @eriknordmark and @OhmSpectator 

## Description of the error

If a container image (not a disk VM) was downloaded and in verification or verified, but not yet loaded into the content-addressable-store, i.e. containerd, and the device reboots, upon reboot it loads the image incorrectly into containerd, thinking it is a disk. It then tries to create a snapshot and fails with an error like:

```
failed to extract layer sha256:3a46589e93913901d4487d6964fa82deeb7cfbed293f3be00ca27da8556f6aa9: failed to get stream processor for application/vnd.lfedge.disk.layer.v1+raw: no processor for media-type: unknown"
```

The key indicator in the logs is the above, when we know that this digest is for a a container image, not a disk, yet it believes it to be a disk by media-type. It then tries to build a snapshot with it, which cannot be done except with a layer.

## Cause

1. The device reboots
2. Tries to restore lots of stuff, especially out of `/persist`. Mostly, this works fine.
3. Sees that there is a content tree in download process request (or does anew, it doesn’t matter)
4. Tries to find `BlobStatus` for the root blob using `lookupOrCreateBlobStatus()` [here](https://github.com/lf-edge/eve/blob/3db87c6f9806a5ae5e565c21299f638694523a44/pkg/pillar/cmd/volumemgr/handlecontent.go#L192). Function is defined [here](https://github.com/lf-edge/eve/blob/master/pkg/pillar/cmd/volumemgr/blob.go#L403).
5. It looks up the blob status [here](https://github.com/lf-edge/eve/blob/master/pkg/pillar/cmd/volumemgr/blob.go#L409), does not find it, so it looks for a `VerifyImageStatus` [here](https://github.com/lf-edge/eve/blob/master/pkg/pillar/cmd/volumemgr/blob.go#L419).
6. Most of the time, it does not find one, so it goes backwards, eventually redownloading; those cases are fine.
7. In the circumstance outlined above, it _does_ find a `VerifyImageStatus`, so it creates a `BlobStatus` and publishes it [here](https://github.com/lf-edge/eve/blob/master/pkg/pillar/cmd/volumemgr/blob.go#L419). This `BlobStatus` does not contain a media-type, which is defined as a property of `BlobStatus` [here](https://github.com/lf-edge/eve/blob/master/pkg/pillar/types/blob.go#L36).
8. Now we have a `BlobStatus`, but the remaining flow no longer knows the media type for that image. Of course, _we_ know that it is an OCI image manifest, but EVE does not.
9. When it comes time to determine if this is a manifest or not (i.e. a VM disk, although in the future, could be something else), and so if it needs to be wrapped with a manifest, it calls `IsManifest()` [here](https://github.com/lf-edge/eve/blob/3db87c6f9806a5ae5e565c21299f638694523a44/pkg/pillar/cmd/volumemgr/updatestatus.go#L315), defined [here](https://github.com/lf-edge/eve/blob/master/pkg/pillar/types/blob.go#L68), which checks the media-type, finds none, and says, “it definitely is not a manifest”
10. It gets wrapped by a new manifest saying it is a disk, and the rest is history

Normally, we get the media type as part of the download, it gets passed to the verify process, which then sets it on the `BlobStatus`, see [here](https://github.com/lf-edge/eve/blob/3db87c6f9806a5ae5e565c21299f638694523a44/pkg/pillar/cmd/volumemgr/blob.go#L196). It does not preserve that into the `VerifyStatus`.

However, when we restore after a reboot when the download status no longer exists, that bit of info is lost, and we recreate the `BlobStatus` _without_ adding the media-type.

## Potential solution

1. Carry the media type from the download into the `VerifyStatus`, when we set it on `BlobStatus`, which is lost on reboot. It cannot hurt.
2. On reboot, when we set the `BlobStatus` from the `VerifyStatus`, populate it from there.

The above assumes that the `VerifyStatus` persists through reboot. That may not be correct.

## Summary

One critical piece of information - a blob's media-type - is passed from the downloader (retrieves it via the content header) to the `BlobStatus`, but is lost on reboot. This works if we download all over again, or completed download+verify+load - all or none. If we pick it up again in the middle, we lose that information. We need to find a way to persist that information across reboots.

### PR DESCRIPTION
**Pull request by deitch**
Fixes #3704 

(or at least tries to; need feedback from @eriknordmark and @OhmSpectator)

Important note: there is a need for a more comprehensive review of how state persists across reboots. This does not solve that. It just solves the need to resolve a very particular issue.

As described in #3704, if a blob from an OCI image was downloaded and either in verifying or verified, but not yet loaded into CAS, and the device reboots, the media-type gets lost. It only was retrieved using `Content-Type` during download, passed to `BlobStatus`, but that is lost on reboot. When it reconstructs `BlobStatus` after reboot from `VerifyImageStatus`, it has lost the media-type. This causes EVE to misinterpret what the blob is and be unable to use it.

This fix does the following:

* Add `MediaType` to `VerifyImageConfig` and `VerifyImageStatus`
* When creating the verifier filename (both verifier stage and verified stage), create an escaped suffix to the filename. This mostly is ignored, _except_ when recreating a `VerifyImageStatus` if none exists, i.e. post-reboot.
* Carry the `MediaType` from `VerifyImageStatus` to `BlobStatus` post-reboot, which lets it be loaded correctly.

### CODE REVIEW

**Comment by deitch** [comment]
cc @OhmSpectator @eriknordmark for detailed look.

**Comment by deitch** [comment]
I just realized, of course, base64 is unsafe for a filename, as it can include `/`. I will update it.

File: pkg/pillar/cmd/verifier/verifier.go [hunk 1]
```diff
@@ -308,9 +309,11 @@ func handleCreate(ctx *verifierContext,
 	status := types.VerifyImageStatus{
 		Name:        config.Name,
 		ImageSha256: config.ImageSha256,
+		MediaType:   config.MediaType,
 		PendingAdd:  true,
 		State:       types.VERIFYING,
 		RefCount:    config.RefCount,
+		MediaTyoe:   config.MediaType,
```
Comment (OhmSpectator) [inline pkg/pillar/cmd/verifier/verifier.go:316]: It's a typo, I guess?

**Review by OhmSpectator — COMMENTED** [review]
I'll take the code to test it with my script.

File: pkg/pillar/cmd/verifier/verifier.go (hunk 1 above)
Comment (deitch) [reply pkg/pillar/cmd/verifier/verifier.go]: I thought I had fixed that! OK, fixed now.

File: pkg/pillar/cmd/verifier/verifier.go [hunk 2]
```diff
@@ -308,9 +309,11 @@ func handleCreate(ctx *verifierContext,
 	status := types.VerifyImageStatus{
 		Name:        config.Name,
 		ImageSha256: config.ImageSha256,
+		MediaType:   config.MediaType,
 		PendingAdd:  true,
 		State:       types.VERIFYING,
 		RefCount:    config.RefCount,
+		MediaType:   config.MediaType,
```
Comment (OhmSpectator) [inline pkg/pillar/cmd/verifier/verifier.go:316]: Is it duplicating 312?..

**Comment by deitch** [comment]
base64 was not right for this. I used [url.PathEscape](http://pkg.go.dev/net/url#PathEscape) and `url.PathUnescape` instead.

File: pkg/pillar/cmd/verifier/verifier.go [hunk 3]
```diff
@@ -609,10 +614,21 @@ func handleInitVerifiedObjects(ctx *verifierContext) {
...
 
+	// filename might have two parts, separated by '.': digest and base64(mediaType)
+	var (
+		mediaType string
+		digest    string
+	)
+	parts := strings.Split(imageFileName, ".")
+	digest = parts[0]
+	if len(parts) == 2 {
+		mediaType = url.PathUnescape(parts[1])
```
Comment (OhmSpectator) [inline pkg/pillar/cmd/verifier/verifier.go:625]: Should we verify the string here? 
Or use just the int value, as we do here?
Maybe we can use just the int value that corresponds to the type?
Like we do here?
https://github.com/lf-edge/eve/blob/5a06e7997aa9e85c94ab539eaed3b09f7d1721d4/pkg/pillar/cmd/volumemgr/initialvolumestatus.go#L141

File: pkg/pillar/cmd/verifier/verifier.go (hunk 2 above)
Comment (deitch) [reply pkg/pillar/cmd/verifier/verifier.go:316]: Yeah, my fault. Got confused. Fixing.

File: pkg/pillar/cmd/verifier/verifier.go (hunk 3 above)
Comment (deitch) [reply pkg/pillar/cmd/verifier/verifier.go:625]: I really prefer not to. This is a media-type, it could mean lots of things, including those of which perhaps EVE is unaware. These should be passed through as is.

**Comment by OhmSpectator** [comment]
I've fixed the compilation errors and set the tests.

File: pkg/pillar/cmd/verifier/verifier.go [hunk 4]
```diff
@@ -609,10 +613,22 @@ func handleInitVerifiedObjects(ctx *verifierContext) {
 func verifyImageStatusFromImageFile(imageFileName string,
 	size int64, pathname string) *types.VerifyImageStatus {
 
+	// filename might have two parts, separated by '.': digest and base64(mediaType)
```
Comment (eriknordmark) [inline pkg/pillar/cmd/verifier/verifier.go:616]: base64 no longer correct.
Also please add something saying that the media type can be missing after an upgrade from previous versions of EVE-OS.

**Comment by OhmSpectator** [comment]
Twenty-two test cycles passed successfully so far. The previous max without the fix was eight, usually less. So I would consider the fix working.

File: pkg/pillar/cmd/verifier/verifier.go (hunk 4 above)
Comment (deitch) [reply pkg/pillar/cmd/verifier/verifier.go]: > Also please add something saying that the media type can be missing after an upgrade from previous versions of EVE-OS

I can see a scenario where it happens during any reboot, not just upgrade. The timing has to be just right (or wrong), though.

Comment added.

File: pkg/pillar/cmd/verifier/verifier.go [hunk 5]
```diff
@@ -609,10 +619,22 @@ func handleInitVerifiedObjects(ctx *verifierContext) {
...
 	size int64, pathname string) *types.VerifyImageStatus {
 
+	// filename might have two parts, separated by '.': digest and PathEscape(mediaType)
+	var (
+		mediaType string
+		digest    string
+	)
+	parts := strings.Split(imageFileName, ".")
+	digest = parts[0]
+	if len(parts) == 2 {
```
Comment (OhmSpectator) [inline pkg/pillar/cmd/verifier/verifier.go:629]: By the way, can we set the type somehow heuristically if it lacks? To prevent the failure when updating to the new version with the fix.

This part will work only after we save the media type in the filename with the fixed version. When rebooting to the fixed version from the previous version without the fix - it would be nice to have somehow restoration logic or at least to let the user know that it's a kind of expected failure.

Comment (deitch) [reply pkg/pillar/cmd/verifier/verifier.go:629]: > By the way, can we set the type somehow heuristically if it lacks? To prevent the failure when updating to the new version with the fix

We could try, but I suspect it is fraught with errors. We may try processing too large a file, or make a mistake, etc. It might just be cleaner to have this be a known error and fail for it, rather than trying to guess our way through.

Comment (OhmSpectator) [reply pkg/pillar/cmd/verifier/verifier.go:629]: Can't we return an error and force the download/verification process again?

**Review by OhmSpectator — COMMENTED** [review]
I would like to suggest a commit message that would be useful for future traceability of the change:
```
pillar: Encode media type in verifier filenames.

Implemented a feature to save the media type base64 hashed in the
verifier filename. This enhancement is used in both config and
status, ensuring that the media type is persistently available and
survives reboots. Modified several functions in verifier.go to
include media type in the filename generation. Also updated
related structures in verifiertypes.go to include the media type.

Issue: #3704 
```

**Comment by OhmSpectator** [comment]
I've tried to find the unit tests that we use for the Verifier component to add several new test cases. I see a bunch of data that can be used for the tests here: https://github.com/lf-edge/eve/blob/13671615437eb604677af96c00c2daef947167f1/pkg/pillar/cmd/verifier/testdata, but I do not see how it's used.
Do you have any ideas about how we test this component? @deitch, @eriknordmark, @milan-zededa, @uncleDecart?

File: pkg/pillar/cmd/verifier/verifier.go (hunk 5 above)
Comment (deitch) [reply pkg/pillar/cmd/verifier/verifier.go:629]: I think that is valid. Or maybe return a validation error, and whatever happens afterwards is the normal flow. But where do we do that?

**Comment by deitch** [comment]
> I would like to suggest a commit message that would be useful for future traceability of the change:

Sure, I will modify the commit message.

**Comment by deitch** [comment]
Updated commit message.

**Comment by deitch** [comment]
> I've tried to find the unit tests that we use for the Verifier component to add several new test cases. I see a bunch of data that can be used for the tests here: https://github.com/lf-edge/eve/blob/13671615437eb604677af96c00c2daef947167f1/pkg/pillar/cmd/verifier/testdata, but I do not see how it's used.
Do you have any ideas about how we test this component?

Unfortunately not. It is very hard to test these things because they depend on pubsub, interfaces, and being inside EVE. It isn't strictly necessary, it just is the way it has been until now.

If you look at eve-libs, many of those things were inside various parts of pillar, and were pulled out (when we had a chance), so they could be standalone libraries, and thus testable. The goal was to do those here as well; remains a goal to this day.

There _is_ a `testdata/` dir, with some artifacts, and I remember creating them, but I do not recall where or how they are used. A quick search shows no references.

File: pkg/pillar/cmd/verifier/verifier.go (hunk 5 above)
Comment (OhmSpectator) [reply pkg/pillar/cmd/verifier/verifier.go:629]: As far as I understand, if we return the nil status here, no VerifierStatus will not be populated and published:
https://github.com/lf-edge/eve/blob/304dc155230b4244dc9506d36ecacfa7e8be5b19/pkg/pillar/cmd/verifier/verifier.go#L685

In this case the check here
https://github.com/lf-edge/eve/blob/master/pkg/pillar/cmd/volumemgr/blob.go#L419
will not pass, and the BlobStatus will not be populated leading to, according to your comment here (https://github.com/lf-edge/eve/issues/3704#issue-2081568716), a regular fallback mechanism, that workers fine. So, I would test returning nil.

**Comment by OhmSpectator** [comment]
> Unfortunately not. It is very hard to test these things because they depend on pubsub, interfaces, and being inside EVE. 

I thought about adding several simple unit tests for how the filenames are generated and how they are parsed later. Not full-scale integration tests (that are up to ztets/eden).

**Comment by deitch** [comment]
If you have a simple way, go for it.

File: pkg/pillar/cmd/verifier/verifier.go (hunk 5 above)
Comment (OhmSpectator) [reply pkg/pillar/cmd/verifier/verifier.go:629]: I'll test this approach locally now.

Comment (OhmSpectator) [reply pkg/pillar/cmd/verifier/verifier.go:629]: I've tested it with several iterations, and it looks like it works. In this case, the application does not fail to start after the reboot. So, let's return nil here.

Comment (eriknordmark) [reply pkg/pillar/cmd/verifier/verifier.go:629]: @OhmSpectator you mean returning nil when there is len(parts) != 2?
Or returning nil when the mediaType string is an empty string?
(I don't know whether some local https datastore will set the content-type header.)

File: pkg/pillar/cmd/verifier/verifier.go [hunk 6]
```diff
@@ -500,12 +502,20 @@ func handleGlobalConfigDelete(ctxArg interface{}, key string,
...
+// it around in the status (DownloadStatus -> BlobStatus), but those are ephemeral and
+// lost during a reboot. We need that information to be persistent and survive reboot,
+// so we can reconstruct it. Hence, we preserve it in the filename. It is PathEscape'd
+// so it is filename-safe.
+func ImageVerifierFilenames(infile, sha256, tmpID, mediaType string) (string, string, string) {
 	verifierDirname, verifiedDirname := getVerifierDir(), getVerifiedDir()
 	// Handle names which are paths
-	verified := tmpID + "." + sha256
-	return infile, path.Join(verifierDirname, verified), path.Join(verifiedDirname, sha256)
+	mediaTypeSafe := url.PathEscape(mediaType)
```
Comment (OhmSpectator) [inline pkg/pillar/cmd/verifier/verifier.go:515]: I see the test passing, but I'm confused about how that works if we _change_ the media type here and encode it in the filename. Later, we just read it without any decoding... Especially taking into account that we have pretty complex media types like "application/vnd.docker.distribution.manifest.v2+json""

File: pkg/pillar/cmd/verifier/verifier.go (hunk 5 above)
Comment (OhmSpectator) [reply pkg/pillar/cmd/verifier/verifier.go:629]: I mean returning nil if len(parts) != 2

File: pkg/pillar/cmd/verifier/verifier.go (hunk 6 above)
Comment (OhmSpectator) [reply pkg/pillar/cmd/verifier/verifier.go:515]: Argh, sorry, we use an unescape function on reading...
Ok, I'll add a unit test to verify the entire chain of encoding-decoding.

Comment (deitch) [reply pkg/pillar/cmd/verifier/verifier.go:515]: We recognize that we made a silly mistake and fix it!

Comment (deitch) [reply pkg/pillar/cmd/verifier/verifier.go:515]: Take a look now.

Comment (OhmSpectator) [reply pkg/pillar/cmd/verifier/verifier.go:515]: I'm concerned now about the reliability of my test script, that did not show any problem in 23 iterations the previous night...

**Comment by OhmSpectator** [comment]
@deitch, don't you mind if I push a simple unit test to the same branch as a separate commit?

**Comment by deitch** [comment]
Go for it.

**Comment by OhmSpectator** [comment]
ok, will do now

**Comment by OhmSpectator** [comment]
By the way, the test fails:
```shell
INFO[0000] Containerd Init                              
--- FAIL: TestMediaTypeInStatus (0.00s)
    verifier_test.go:24: MediaType in status dummySha256.application/vnd.docker.distribution.manifest.v2+json does not match original application/vnd.docker.distribution.manifest.v2+json
FAIL
exit status 1
FAIL    github.com/lf-edge/eve/pkg/pillar/cmd/verifier  0.014s
```

**Comment by deitch** [comment]
I cannot figure out where I let you push to my branch. There used to be a setting on a PR for that.

**Comment by deitch** [comment]
I tried by sending you an invite to my fork @OhmSpectator , let us see if that works.

**Comment by OhmSpectator** [comment]
If you don't find how to let it, you can add a commit yourself.
The file I've shown in the previous commit and the commit message would be:
```
pillar: Add unit tests for media type encoding/decoding in Verifier.
    
This commit introduces new unit tests in verifier_test.go for the verifier
module. The tests focus on ensuring that media types, specifically
'application/vnd.docker.distribution.manifest.v2+json', are correctly encoded
into file names and then accurately decoded back into the VerifyImageStatus
structure.
    
```

**Comment by deitch** [comment]
I see you accepted. Try to push?

**Comment by deitch** [comment]
It worked!

**Comment by OhmSpectator** [comment]
Yeah, cool, it works! Thanks!

**Comment by OhmSpectator** [comment]
So, the current problem is that the SHA part of the filename is falsely parsed as a part of the media type. See comment here: https://github.com/lf-edge/eve/pull/3706#issuecomment-1896168371.
So, I have to retest it tomorrow with the fixed code. And I will also think about proving that the code was triggered during the testing and the issue is gone...

**Comment by deitch** [comment]
@OhmSpectator I think your test is incorrect. `verifyImageStatusFromFilename()` is supposed to take a _verified_ filename, not a _verifier_ filename.

It gets called [here](https://github.com/lf-edge/eve/blob/3db87c6f9806a5ae5e565c21299f638694523a44/pkg/pillar/cmd/verifier/verifier.go#L661), which is in `populateInitialStatusFromVerified()` (not from verifier).

I think the test is supposed to be:

```go
func TestMediaTypeInStatus(t *testing.T) {
	mediaType := "application/vnd.docker.distribution.manifest.v2+json"
	tmpID := "tempID"
	sha256 := "dummySha256"
	infile := "dummyFile"

	_, _, verifiedFilename := ImageVerifierFilenames(infile, sha256, tmpID, mediaType)
	print("verifiedFilename: ", verifiedFilename)

	status := verifyImageStatusFromImageFile(verifiedFilename, 12345, "dummyPath")

	if status == nil {
		t.Fatalf("Status is nil")
	}

	if status.MediaType != mediaType {
		t.Errorf("MediaType in status %v does not match original %v", status.MediaType, mediaType)
	}
}
```

**Comment by OhmSpectator** [comment]
Yep, I'll fix it. But if I'm not mistaken, I tried this option as well, and it also failed. But I may be wrong and will retest soon.

**Comment by OhmSpectator** [comment]
Yep, I was wrong. The test passes if the verifiedFilenam is used.
But it looks like an error-prone piece. Maybe we should add a note to the comment to the ImageVerifierFilenames function:
```
// ImageVerifierFilenames - Returns pendingFilename, verifierFilename, verifiedFilename
// for the image. Both verifierFilename and verifiedFilename include an extension
// of the media-type, e.g., abcdeff112.application-vnd.oci.image.manifest.v1+json.
// This inclusion is essential as we need the media-type to process the blob. 
// Normally, we carry it in the status (DownloadStatus -> BlobStatus), but these
// statuses are ephemeral and lost during a reboot. To ensure persistence and 
// survival through reboots, we embed the media-type in the filename, making it
// filename-safe using PathEscape.
//
// Note: The code in verifyImageStatusFromImageFile for extracting and verifying 
// media type is applicable only for verifiedFilename. This specific implementation
// should not be reused for verifierFilename, as the logic and format for handling 
// media types in verifierFilename might differ. If future requirements necessitate 
// handling media types in verifierFilename, separate logic should be developed.
```

The other option - it make code of parsing suitable for the both cases.

**Comment by OhmSpectator** [comment]
If there is no any reason to check the media type in the verifying case, then maybe not add it to the corresponding filename?
All these notes are not critical, but I want to make the code as little confusing as possible.  Meanwhile, I'm preparing a new test run.

**Comment by deitch** [comment]
> If there is no any reason to check the media type in the verifying case, then maybe not add it to the corresponding filename?

To be honest, I wasn't sure. I thought maybe we do pick it up from there somewhere, or might at one point. And we like these to be parallel, except for the leading tmp string (which is there because of potential conflicts IIRC). So I added it. I would like to leave it for now.

File: pkg/pillar/cmd/verifier/verifier.go (hunk 5 above)
Comment (eriknordmark) [reply pkg/pillar/cmd/verifier/verifier.go:629]: @OhmSpectator That means if we have an image in /persist/vault/verified/ from before an EVE update to these bits, we will redownload it. That should be fine for that corner case.
But do we end up garbage collecting that old image, or can it stick around forever?

**Comment by OhmSpectator** [comment]
> I would like to leave it for now.
I got it, no problem. In this case, I think we should explicitly warn against reusing the current parsing implementation for any future parsing of the verifying filename, to avoid confusion:
```
// Note: The code in verifyImageStatusFromImageFile for extracting and verifying 
// media type is applicable only for verifiedFilename. This specific implementation
// should not be reused for verifierFilename, as the logic and format for handling 
// media types in verifierFilename might differ. If future requirements necessitate 
// handling media types in verifierFilename, separate logic should be developed.
```

File: pkg/pillar/cmd/verifier/verifier.go (hunk 5 above)
Comment (OhmSpectator) [reply pkg/pillar/cmd/verifier/verifier.go:629]: Good point! The purpose was to force the redownload, exactly. I forgot about the garbage file in this case.  I'll think about the proper cleanup. FYI, @deitch.

Comment (deitch) [reply pkg/pillar/cmd/verifier/verifier.go:629]: @OhmSpectator go for it. I pushed out changes based on your other comments, so don't forget to `pull` before `commit && push`

**Comment by OhmSpectator** [comment]
@deitch, I'm pulling the newest version of the PR, but I do not see any changes... Hopefully, it was not overwritten when I pushed my fix for the unit test...

**Review by eriknordmark — COMMENTED** [review]
Is there still an issue with dots in the media type?

You can avoid those by switching to base64.URLEncoding.EncodeToString()

**Comment by deitch** [comment]
> Hopefully, it was not overwritten when I pushed my fix for the unit test...

Looks like it was. Don't do anything until I do another push. One minute.

**Comment by deitch** [comment]
OK, fixed it. Pull now @OhmSpectator

**Comment by deitch** [comment]
> You can avoid those by switching to base64.URLEncoding.EncodeToString()

base64 does not work, because it allows `/` in it, which would mean escaping it anyways, so I switched to URL path encoding. It works.

**Comment by deitch** [comment]
> Is there still an issue with dots in the media type?

Nope. We switched from `strings.Split(filename, ".")` to `string.SplitN(filename, ".", 2)`

**Comment by OhmSpectator** [comment]
> Looks like it was. Don't do anything until I do another push. One minute.
Oops, sorry. I really had fetched the latest version 10 seconds before pushing the fix. We were lucky =D

**Comment by eriknordmark** [comment]
> base64 does not work, because it allows `/` in it, which would mean escaping it anyways, so I switched to URL path encoding. It works.

FWIW URLEncoding does not use /. StdEncoding uses /.

File: pkg/pillar/cmd/verifier/verifier.go (hunk 5 above)
Comment (OhmSpectator) [reply pkg/pillar/cmd/verifier/verifier.go:632]: I've added a change to address the cleanup and the redownload process.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by OhmSpectator** [comment]
I'll now push one more small commit with the addition of a log line.

**Comment by OhmSpectator** [comment]
I've added a commit with an extra log line and squashed the two commits that added the unit test.

**Comment by OhmSpectator** [comment]
It is strange that a very simple log message crashes the test now... Checking and fixing. I guess I've made a stupid error.

**Comment by OhmSpectator** [comment]
Argh... The problem is that the logger is not initialized if run in a testing environment with `go test`... Fixing..

**Comment by OhmSpectator** [comment]
I fixed the logger issue in the unit test. Also, I added a new unit test for the absent media type case.

**Review by OhmSpectator — APPROVED** [review]
I executed over 50 test cycles. Though I'm unable to see the new logs, at least it isn't failing. I believe we can merge it.
